# --------------------------------

alias      ga='git add'
alias      gb='git branch'
alias     gbr='git branch -r'
alias    gbrv='git branch -rv'
alias    gout='git checkout'
alias      gc='git commit'
alias      gd='git diff'
alias    gfom='git fetch origin master'
alias  gmmast='git merge master'
alias  gmmain='git merge main'
alias      gs='git status'
alias gpumain='git push origin main'
alias gpumast='git push origin master'
alias     gpo='git push origin'
alias gplmain='git pull origin main'
alias gplmast='git pull origin master'
alias      gr='git remote'
alias     grv='git remote -v'
alias    gruo='git remote update origin'
alias   gruop='git remote update origin --prune'
alias      gt='git tag'
alias     gtt='git tag | tail -8'

# --------------------------------
