---
- name: ansible-role-app-aptmirror
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-aptmirror"
  version: "2.2.1"
- name: ansible-role-app-brave
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-brave"
  version: "1.3.0"
- name: ansible-role-app-clamav
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-clamav"
  version: "1.1.0"
- name: ansible-role-app-datadog
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-datadog"
  version: "2.10.1"
- name: ansible-role-app-dnsmasq
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-dnsmasq"
  version: "3.2.1"
- name: ansible-role-app-docker
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-docker"
  version: "1.7.2"
- name: ansible-role-app-duoauthproxy
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-duoauthproxy"
  version: "0.1.0"
- name: ansible-role-app-envoy
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-envoy"
  version: "3.3.1"
- name: ansible-role-app-fail2ban
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-fail2ban"
  version: "1.7.2"
- name: ansible-role-app-freeradius
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-freeradius"
  version: "1.0.1"
- name: ansible-role-app-gitlab
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-gitlab"
  version: "0.7.1"
- name: ansible-role-app-grafana
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-grafana"
  version: "1.9.0"
- name: ansible-role-app-granulate
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-granulate"
  version: "1.1.0"
- name: ansible-role-app-jenkins
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-jenkins"
  version: "1.2.2"
- name: ansible-role-app-kafka
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-kafka"
  version: "0.5.0"
- name: ansible-role-app-mongodb
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-mongodb"
  version: "1.0.0"
- name: ansible-role-app-nginx
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-nginx"
  version: "1.5.1"
- name: ansible-role-app-opengrok
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-opengrok"
  version: "2.0.0"
- name: ansible-role-app-pritunl
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-pritunl"
  version: "1.0.0"
- name: ansible-role-app-tor
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-tor"
  version: "1.1.0"
- name: ansible-role-app-zookeeper
  scm: git
  src: "https://github.com/cabtech/ansible-role-app-zookeeper"
  version: "0.3.0"
- name: ansible-role-crypto-bitcoinnode
  scm: git
  src: "https://github.com/cabtech/ansible-role-crypto-bitcoinnode"
  version: "0.0.1"
- name: ansible-role-crypto-opendax
  scm: git
  src: "https://github.com/cabtech/ansible-role-crypto-opendax"
  version: "0.0.1"
- name: ansible-role-crypto-sui
  scm: git
  src: "https://github.com/cabtech/ansible-role-crypto-sui"
  version: "0.1.0"
- name: ansible-role-distro-centos
  scm: git
  src: "https://github.com/cabtech/ansible-role-distro-centos"
  version: "1.0.0"
- name: ansible-role-distro-ubuntu
  scm: git
  src: "https://github.com/cabtech/ansible-role-distro-ubuntu"
  version: "1.0.1"
- name: ansible-role-family-debian
  scm: git
  src: "https://github.com/cabtech/ansible-role-family-debian"
  version: "1.0.1"
- name: ansible-role-family-redhat
  scm: git
  src: "https://github.com/cabtech/ansible-role-family-redhat"
  version: "1.0.0"
- name: ansible-role-hashicorp-common
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-common"
  version: "2.2.0"
- name: ansible-role-hashicorp-consul
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-consul"
  version: "2.10.0"
- name: ansible-role-hashicorp-nomad
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-nomad"
  version: "3.8.0"
- name: ansible-role-hashicorp-terraform
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-terraform"
  version: "1.1.0"
- name: ansible-role-hashicorp-vault
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-vault"
  version: "3.1.2"
- name: ansible-role-hashicorp-vaultmanager
  scm: git
  src: "https://github.com/cabtech/ansible-role-hashicorp-vaultmanager"
  version: "1.1.1"
- name: ansible-role-opsys-unix
  scm: git
  src: "https://github.com/cabtech/ansible-role-opsys-unix"
  version: "2.3.2"
- name: ansible-role-util-certbot
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-certbot"
  version: "1.8.0"
- name: ansible-role-util-debug
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-debug"
  version: "1.1.0"
- name: ansible-role-util-facts
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-facts"
  version: "1.2.3"
- name: ansible-role-util-gcloud
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-gcloud"
  version: "1.2.0"
- name: ansible-role-util-git
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-git"
  version: "1.1.0"
- name: ansible-role-util-openjdk
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-openjdk"
  version: "1.1.1"
- name: ansible-role-util-osbootstrap
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-osbootstrap"
  version: "1.0.2"
- name: ansible-role-util-python
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-python"
  version: "1.0.0"
- name: ansible-role-util-rust
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-rust"
  version: "1.1.0"
- name: ansible-role-util-rvm
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-rvm"
  version: "0.0.1"
- name: ansible-role-util-security
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-security"
  version: "1.1.0"
- name: ansible-role-util-sublime
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-sublime"
  version: "1.0.0"
- name: ansible-role-util-terragen
  scm: git
  src: "git@github.com/cabtech/ansible-role-util-terragen.git"
  version: "1.0.0"
- name: ansible-role-util-user
  scm: git
  src: "https://github.com/cabtech/ansible-role-util-user"
  version: "1.7.0"
...
